// <auto-generated />
using System;
using FoodDbAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDbAPI.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20250608013529_MealCreation")]
    partial class MealCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodDbAPI.Models.Fddb.FddbFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Ean")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("TagsJson");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Name");

                    b.ToTable("FddbFoods");
                });

            modelBuilder.Entity("FoodDbAPI.Models.Fddb.FddbFoodNutrition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalciumUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CalciumValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CaloriesUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CaloriesValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CarbohydratesPolyolsUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CarbohydratesPolyolsValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CarbohydratesSugarUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CarbohydratesSugarValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CarbohydratesTotalUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CarbohydratesTotalValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ChlorideUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ChlorideValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CopperUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("CopperValue")
                        .HasColumnType("double precision");

                    b.Property<string>("FatUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FatValue")
                        .HasColumnType("double precision");

                    b.Property<int>("FddbFoodId")
                        .HasColumnType("integer");

                    b.Property<string>("FiberUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FiberValue")
                        .HasColumnType("double precision");

                    b.Property<string>("FluorideUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FluorideValue")
                        .HasColumnType("double precision");

                    b.Property<string>("IodineUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("IodineValue")
                        .HasColumnType("double precision");

                    b.Property<string>("IronUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("IronValue")
                        .HasColumnType("double precision");

                    b.Property<string>("KilojoulesUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("KilojoulesValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MagnesiumUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MagnesiumValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ManganeseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ManganeseValue")
                        .HasColumnType("double precision");

                    b.Property<string>("PhosphorusUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PhosphorusValue")
                        .HasColumnType("double precision");

                    b.Property<string>("PotassiumUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PotassiumValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ProteinUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProteinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SaltUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SaltValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SulfurUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SulfurValue")
                        .HasColumnType("double precision");

                    b.Property<string>("ZincUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ZincValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FddbFoodId")
                        .IsUnique();

                    b.ToTable("FddbFoodNutritions");
                });

            modelBuilder.Entity("FoodDbAPI.Models.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Fat")
                        .HasColumnType("double precision");

                    b.Property<int>("FddbFoodId")
                        .HasColumnType("integer");

                    b.Property<double>("Fiber")
                        .HasColumnType("double precision");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FoodUrl")
                        .HasColumnType("text");

                    b.Property<double>("GramsConsumed")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double>("Sugar")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FddbFoodId");

                    b.HasIndex("UserId", "ConsumedAt");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("FoodDbAPI.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("FoodDbAPI.Models.MealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FddbFoodId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FddbFoodId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems");
                });

            modelBuilder.Entity("FoodDbAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CurrentWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodDbAPI.Models.UserWeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("FoodDbAPI.Models.Fddb.FddbFoodNutrition", b =>
                {
                    b.HasOne("FoodDbAPI.Models.Fddb.FddbFood", "FddbFood")
                        .WithOne("Nutrition")
                        .HasForeignKey("FoodDbAPI.Models.Fddb.FddbFoodNutrition", "FddbFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FddbFood");
                });

            modelBuilder.Entity("FoodDbAPI.Models.FoodEntry", b =>
                {
                    b.HasOne("FoodDbAPI.Models.Fddb.FddbFood", "FddbFood")
                        .WithMany()
                        .HasForeignKey("FddbFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDbAPI.Models.User", "User")
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FddbFood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDbAPI.Models.Meal", b =>
                {
                    b.HasOne("FoodDbAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDbAPI.Models.MealItem", b =>
                {
                    b.HasOne("FoodDbAPI.Models.Fddb.FddbFood", "FddbFood")
                        .WithMany()
                        .HasForeignKey("FddbFoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodDbAPI.Models.Meal", "Meal")
                        .WithMany("MealItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FddbFood");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FoodDbAPI.Models.UserWeightEntry", b =>
                {
                    b.HasOne("FoodDbAPI.Models.User", "User")
                        .WithMany("WeightEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDbAPI.Models.Fddb.FddbFood", b =>
                {
                    b.Navigation("Nutrition")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDbAPI.Models.Meal", b =>
                {
                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("FoodDbAPI.Models.User", b =>
                {
                    b.Navigation("FoodEntries");

                    b.Navigation("WeightEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
