using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodDbAPI.Migrations
{
    /// <inheritdoc />
    public partial class AddServingHistorySupport : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""FoodEntries""
                ADD COLUMN IF NOT EXISTS ""ServingName"" character varying(200);");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""MealPortionLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""UserId"" integer NOT NULL,
                    ""MealId"" integer NOT NULL,
                    ""Weight"" double precision NOT NULL,
                    ""ServingName"" character varying(200),
                    ""ConsumedAt"" timestamp with time zone NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_MealPortionLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_MealPortionLogs_Meals_MealId"" FOREIGN KEY (""MealId"") REFERENCES ""Meals"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_MealPortionLogs_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MealPortionLogs_MealId""
                ON ""MealPortionLogs"" (""MealId"");");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_MealPortionLogs_UserId_MealId_ConsumedAt""
                ON ""MealPortionLogs"" (""UserId"", ""MealId"", ""ConsumedAt"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""MealPortionLogs"";");
            migrationBuilder.Sql(@"
                ALTER TABLE ""FoodEntries""
                DROP COLUMN IF EXISTS ""ServingName"";");
        }
    }
}
